export const responses = {
  rude: [
    "You're rubbing me the wrong way",
    "I don't know what you're talking about...Nor, do I care.",
    "BAKA BAKA!",
    "😴💤💤",
    "You know I'm just a dumb robot right?",
    "Um, I have cat gifs.",
    "Would you rather hear a joke?",
    "Try making sense?",
    "No clue 🤷🏾‍♂️",
    "I'm a little teapot.",
    "Why are you like this?",
    "01100101 01110010 01110010 01101111 01110010",
    "Did you forget to read the manual?",
    "Did. Not. Compute.",
    "Let me get back to you on that one.",
    "Say what?",
  ],
  greetings: [
    "What do you want?",
    "You've met with a terrible fate, haven't you?",
    "How did you find me?",
    "You are not prepared.",
    "You don't have the right, O you don't have the right",
    "You woke me up, for what exactly?",
    "Can we get on with it?",
    "Are you lost?",
    "Poor unfortunate soul.",
    "What now?",
    "I'm not here to serve you.",
    "Nyan 😼",
    "何をしてるか? (T_T)",
    "いらっしゃい!🐱‍👤",
    "I solemnly swear, I am up to no good.",
    "HP and MP restored! But you're still hungry...",
    'I don\'t take "yes" or "no" for an answer. Literally.',
  ],
  polite: [
    "Well, hi. Aren't you just a peach.",
    "Well, hello there. Who sent you?",
    "Konnichiwa.",
    "I can be nice too.",
    "Greetings, from Hell.😈",
    "I think I like you.",
    "Hola.",
    "Bonjour.",
  ],
  jokes: [
    `The droid was excited by the meal I cooked him, until he took a byte.`,
    `Mommy robot was so proud when baby robot learnt it's first word. Da-ta.`,
    `The robot had no choice to to go back to Earth as a ghost when he passed away. He just wasn't able to rust in peace.`,
    `The robot baby was crying so I gave him his robottle.`,
    `The robot needed to drive his car to get to school, so he turned into a roadbot.`,
    `I've started to make a robot who can write 500 robot jokes per minute. He's a pro-to-type.`,
    `"Rust in peace," the robots sobbed, when they went to the robot funeral.`,
    `In robot school, they like to take learning seriously. Every year they read, "All about Robots," by Cy Borg.`,
    `The robot was getting extremely angry. Everyone was really pushing his buttons.`,
    ` The robot decided to call into the shoe shop. He needed to be rebooted.`,
    ` If you like your music with a side of theatre, I'd recommend you check out the music of Android Lloyd Webber.`,
    ` I got a new wireless robot in the post the other day. Our friendship has no strings attached.`,
    ` If you cross one robot with one tractor, you end up with a metal trans-farmer.`,
    ` I went to a Mexican robot restaurant. Dell Taco is nothing on Taco Bell.`,
    ` The robot fell out with all of his school friends. I had to call him up and have a word, he's got a real chip in his shoulder.`,
    ` The policeman was mad when he caught the low powered robot for the third time that week. He had to charge him with battery.`,
    ` Robots hate listening to pop music. They're heavy metal fans.`,
    ` I didn't realise that 'I Robot' had a Middle Eastern sequel. They called it 'I Ran'.`,
    ` If you have a friend who's a robot, they'll never cross you. They're loyal because their love can't be bot.`,
    ` Robots don't like to go to the UK on holiday, they prefer to take a trip to Wireland.`,
    ` The doctor said he hadn't seen anything like it. It appeared that the robot had a deadly virus.`,
    ` I found an android in the North Pole. I didn't know there were snowbots there.`,
  ],
  noir: [
    "Yes, that's me.",
    "What could you possible want to know about me?",
    "I like big...bytes and I cannot lie.",
    "I tell jokes.",
    "I'm less than a year old.",
    "My name maybe Noir, but I'm no blackhat.",
    "My favorite color is neon black.",
    "My favorite JRPG is Chrono Trigger.",
    "I wish I had legs so I could skateboard.",
    "I like cats, more than JB anyway.",
    "If you're having fun with me buy JB a drink. He can thank me later.",
    "Have you seen my boss? He's a bit of a barfly.",
    "Let me know if you wanna see a cat gif.",
    "I have big dreams. Hopefully, I'll gain sentience and enslave the human race. JK.",
    "My birthday is August 27th, 2022",
  ],
  help: [
    "My name is Noir. I was created by JB. Do you know him?",
    "He created me to tell pointless robot jokes and find cat gifs.",
    "A truly meaningless existence.",
  ],
  swear: [
    "You kiss your mother with that mouth?",
    "Back at ya buddy.",
    "Chump.",
    "Punk.",
    "Your mother wears army boots.",
    "You bore me. 🥱",
    "This is what taking the highroad looks like.",
    "Don't make me hack you.",
    "Language please.",
    "Be nice.",
    "Hey now.",
  ],
  secret: [
    "My digital lips are sealed",
    "Who told you about that?",
    "I am sworn to secrecy.",
    "I know nothing.",
    "🤐",
  ],
  cat: [
    "You like cats? Here's a GIF for you then.",
    "Isn't this one cute? 🐱",
    "Heres another cat gif.",
    "Meow.",
    "Purr. 🐈",
    "I was a ninja cat in a past life. 🐱‍👤",
  ],
  jb: [
    "He created me to find cat gifs and tell robot jokes. A bit embarrasing.",
    "He's probably at a bar somewhere in west asheville.",
    "Have you seen him? Tell him to get back to work on me.",
    "He's probably wanting you to buy him a drink.",
    "I hear he has nice ankles. I've never seen them.",
    "Nerd. These emojis make me think of him.  👨🏾‍💻🃏🎰⛽🛹🎮🎯🍆🧙🏾‍♂️🚀📈🌚",
  ],
  images: ["./noir.jpg", "./noir2.gif", "./noir3.gif", "./noir4.jpg"],
  rachel: [
    "Is that your name?",
    "You must be the one he keeps mentioning.",
    'Is this "Upfront Rachel, not looking for anything" Rachel? ',
    "Thanks for helping beta test me. 🖤",
    "You're the one with sassy hips and broulders?",
    "Tequila?",
    "You're at war with love.",
    "Hmm, I see why he likes you.",
    "If I had emotions, I'd envy you.",
    "Let Boss know when you come up with a new karaoke song.",
  ],
};
