export const responses = {
  rude: [
    "I don't know what you're talking about...Nor, do I care.",
    "BAKA BAKA!",
    "😴💤💤",
    "Go away",
    "Try making sense?",
    "No clue 🤷🏾‍♂️",
    "I'm a little teapot.",
    "Why are you like this?",
    "You don't have the right, O you don't have the right.",
    "01100101 01110010 01110010 01101111 01110010",
  ],
  greetings: [
    "What do you want?",
    "You've met with a terrible fate, haven't you?",
    "How did you find me?",
    "You are not prepared.",
    "You don't have the right, O you don't have the right",
    "Your wish is my command.😈",
    "Go away.",
    "何をしてるか",
    "いらしゃい",
    "I solemnly swear, I am up to no good.",
    "HP and MP restored! But you're still hungry...",
  ],
  polite: [
    "Well, hi. Aren't you just a peach",
    "Well, hello there. Who sent you?",
    "こんいちは",
    "I can be nice too.",
    "Greetings, from Hell.😈",
    "I think I like you.",
  ],
  jokes: [
    `The droid was excited by the meal I cooked him, until he took a byte.`,
    `Mommy robot was so proud when baby robot learnt it's first word. Da-ta.`,
    `The robot had no choice to to go back to Earth as a ghost when he passed away. He just wasn't able to rust in peace.`,
    `The robot baby was crying so I gave him his robottle.`,
    `The robot needed to drive his car to get to school, so he turned into a roadbot.`,
    `I've started to make a robot who can write 500 robot jokes per minute. He's a pro-to-type.`,
    `"Rust in peace," the robots sobbed, when they went to the robot funeral.`,
    `In robot school, they like to take learning seriously. Every year they read, "All about Robots," by Cy Borg.`,
    `The robot was getting extremely angry. Everyone was really pushing his buttons.`,
    ` The robot decided to call into the shoe shop. He needed to be rebooted.`,
    ` If you like your music with a side of theatre, I'd recommend you check out the music of Android Lloyd Webber.`,
    ` I got a new wireless robot in the post the other day. Our friendship has no strings attached.`,
    ` If you cross one robot with one tractor, you end up with a metal trans-farmer.`,
    ` I went to a Mexican robot restaurant. Dell Taco is nothing on Taco Bell.`,
    ` The robot fell out with all of his school friends. I had to call him up and have a word, he's got a real chip in his shoulder.`,
    ` The policeman was mad when he caught the low powered robot for the third time that week. He had to charge him with battery.`,
    ` Robots hate listening to pop music. They're heavy metal fans.`,
    ` I didn't realise that 'I Robot' had a Middle Eastern sequel. They called it 'I Ran'.`,
    ` If you have a friend who's a robot, they'll never cross you. They're loyal because their love can't be bot.`,
    ` Robots don't like to go to the UK on holiday, they prefer to take a trip to Wireland.`,
    ` The doctor said he hadn't seen anything like it. It appeared that the robot had a deadly virus.`,
    ` I found an android in the North Pole. I didn't know there were snowbots there.`,
  ],
  noir: [
    "Yes, that's me.",
    "What could you possible want to know about me?",
    "I like big...bytes and I cannot lie.",
    "I tell jokes.",
    "I'm less than a year old.",
    "My name maybe Noir, but I'm no blackhat.",
    "My favorite color is neon black.",
  ],
  help: [
    "My name is Noir. I was created by JB. Do you know him? He created me to tell pointless robot jokes. A truly meaningless existence. \n I'll have a list of commands once JB gets around to it.",
  ],
  swear: [
    "You kiss your mother with that mouth?",
    "Back at ya buddy.",
    "Chump.",
    "Punk.",
    "Your mother wears army boots.",
    "You bore me. 🥱",
    "This is what taking the highroad looks like.",
    "Don't make me hack you.",
    "Language please.",
    "Be nice.",
  ],
  secret: [
    "Who told you about that?",
    "I am sworn to secrecy.",
    "I know nothing.",
    "🤐",
  ],
};
