import Head from 'next/head'
import Image from 'next/image'
import Portfolio from './Portfolio'
import Link from 'next/link'
import Navbar from '../components/Navbar';
import Topbar from '../components/Topbar';
import BGImage from '../components/BackgroundImage';

export default function Home() {
  return (
    <div className="text-gray-400 bg-gray-900 body-font bg text-center">
      <Head>
        <title>Josh Bell Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Topbar />
        <div className="flex-row pt-20 text-lg bg-gray-800">
          <Link href="/Portfolio" className="">
            <button className="p-20  transition transform duration-150 hover:scale-150 mt-18">
              About
            </button>
          </Link>
          <br />
          <Link href="/Portfolio#contact" className="">
            <button className="p-20  transition transform duration-150 hover:scale-150">
              Contact
            </button>
          </Link>
          <br />
          <Link href="https://www.github.com/itripleg/" className="">
            <button className="p-20  transition transform duration-150 hover:scale-150 mb-32">
              Github
            </button>
          </Link>          
        </div>
        <footer className="mt-20">© 2021 Joshua Bell, all rights reserved</footer>
    </div>
  )
}
