/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bar(props) {
  const { nodes, materials } = useGLTF("/uwu.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-3.21, 3.43, -5.54]} scale={0.15}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Ground}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.Base}
        />
      </group>
      <group position={[-2.27, 4.79, -6.12]} scale={0.15}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.Ground}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials.Base}
        />
      </group>
      <group position={[-0.56, 0.14, -0.61]} rotation={[0, -0.02, -0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={materials.Secondary}
        />
      </group>
      <group position={[-2.86, 4.79, -5.63]} scale={0.15}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.Secondary}
        />
      </group>
      <group position={[-2.21, 3.39, -5.39]} scale={0.15}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials.Secondary}
        />
      </group>
      <group position={[-1.89, 4.79, -5.08]} scale={0.14}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials.Secondary}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_2.geometry}
          material={materials.Greenish}
        />
      </group>
      <group
        position={[3.19, 6.15, -4.69]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.15}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials.Ground}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_2.geometry}
          material={materials.Base}
        />
      </group>
      <group
        position={[3.78, 6.14, -5.18]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.15}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_2.geometry}
          material={materials.Secondary}
        />
      </group>
      <group
        position={[2.8, 6.15, -5.73]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.14}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials.Secondary}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_2.geometry}
          material={materials.Greenish}
        />
      </group>
      <group position={[-2.75, 3.42, -4.84]} scale={0.15}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_1.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_2.geometry}
          material={materials.Secondary}
        />
      </group>
      <group position={[-2.77, 4.79, -5.2]} scale={0.15}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_2.geometry}
          material={materials.Secondary}
        />
      </group>
      <group
        position={[3.89, 2.11, -5.82]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.15}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_1.geometry}
          material={materials.Ground}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_2.geometry}
          material={materials.Base}
        />
      </group>
      <group
        position={[3.26, 2.1, -5.77]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.15}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.Ground}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_2.geometry}
          material={materials.Base}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Metal}
        position={[-2.33, 0.58, 2.5]}
        scale={0.29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials.Metal}
        position={[-2.33, 1.85, 2.5]}
        scale={[0.42, -0.03, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials.Metal}
        position={[-0.99, 1.71, 2.5]}
        scale={[0.42, -0.03, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials.Metal}
        position={[0.34, 1.71, 2.5]}
        scale={[0.42, -0.03, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials.Metal}
        position={[1.68, 1.71, 2.5]}
        scale={[0.42, -0.03, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials.Metal}
        position={[3.02, 1.71, 2.5]}
        scale={[0.42, -0.03, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials.Metal}
        position={[-0.99, 0.58, 2.5]}
        scale={0.29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials.Metal}
        position={[0.34, 0.58, 2.5]}
        scale={0.29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials.Metal}
        position={[1.68, 0.6, 2.5]}
        scale={0.29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials.Metal}
        position={[3.02, 0.59, 2.5]}
        scale={0.29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={materials.Glass}
        position={[-1.39, 4.53, -5.1]}
        scale={0.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={materials.Glass}
        position={[-1.14, 4.6, -5.1]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028.geometry}
        material={materials.Glass}
        position={[-1.56, 5.96, -5.25]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder029.geometry}
        material={materials.Glass}
        position={[2.06, 3.25, -4.79]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={materials.Glass}
        position={[2.4, 3.32, -4.78]}
        scale={[0.15, 0.24, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={materials.Glass}
        position={[2.47, 4.69, -5.62]}
        scale={[0.15, 0.24, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032.geometry}
        material={materials.Glass}
        position={[-1.63, 3.32, -4.93]}
        scale={[0.15, 0.24, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033.geometry}
        material={materials.Glass}
        position={[0.58, 3.08, 0.37]}
        scale={[0.12, 0.17, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials.Glass}
        position={[3.79, 3.08, -0.6]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder034.geometry}
        material={materials.Glass}
        position={[-2.89, 3.11, -0.41]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder035.geometry}
        material={materials.Glass}
        position={[-2.89, 3.26, -0.41]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder036.geometry}
        material={materials.Glass}
        position={[-2.89, 3.48, -0.41]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder037.geometry}
        material={materials.Glass}
        position={[-1.22, 5.99, -4.9]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder038.geometry}
        material={materials.Glass}
        position={[-1.22, 6.13, -4.9]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder039.geometry}
        material={materials.Glass}
        position={[-1.22, 6.35, -4.9]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder040.geometry}
        material={materials["Metal.001"]}
        position={[-2.33, 0.58, 2.5]}
        scale={0.29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder041.geometry}
        material={materials.Glass}
        position={[-2.56, 3.11, -0.41]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder042.geometry}
        material={materials.Glass}
        position={[-2.56, 3.26, -0.41]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder043.geometry}
        material={materials.Glass}
        position={[-2.56, 3.48, -0.41]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder044.geometry}
        material={materials.Glass}
        position={[-2.2, 3.14, -0.4]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder045.geometry}
        material={materials.Glass}
        position={[-2.2, 3.28, -0.4]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder046.geometry}
        material={materials.Glass}
        position={[-2.2, 3.5, -0.4]}
        scale={[-0.12, -0.17, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.004"]}
        position={[-2.67, 7.66, -6.73]}
        rotation={[-0.47, 0.18, 0.05]}
        scale={[0.87, 0.5, -0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.003"]}
        position={[-3.45, 7.56, -6.35]}
        rotation={[1.11, 0.05, -0.18]}
        scale={0.66}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.004"]}
        position={[1.21, 8.35, -7.05]}
        rotation={[-0.17, 0.15, -0.03]}
        scale={[2.18, 1.26, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder047.geometry}
        material={materials["Material.001"]}
        position={[7.92, 4.05, -3.86]}
        rotation={[-1.48, -0.08, 0.01]}
        scale={0.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[7.15, 1.63, -21.07]}
        scale={[0.9, -0.04, 0.9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bar_body001.geometry}
        material={materials.Wood}
        position={[-2.14, 2, -5.54]}
        scale={[1.43, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground001.geometry}
        material={materials.Wood}
        position={[-0.07, -1.42, -1.33]}
        scale={11.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bar_top.geometry}
        material={materials.Tile}
        position={[-1.99, 1.37, 0.39]}
        scale={1.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground.geometry}
        material={materials.Tile}
        position={[0, 0, -2.79]}
        scale={11.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Image}
        position={[1.21, 8.35, -7.05]}
        rotation={[-0.17, 0.15, -0.03]}
        scale={[2.18, 1.26, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bar_body.geometry}
        material={materials.Marble}
        position={[-1.99, 1.37, 0.39]}
        scale={1.3}
      />
    </group>
  );
}

useGLTF.preload("/uwu.glb");
