/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GreenG (https://sketchfab.com/GreenG)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-electric-guitar-80989fc28011462f81dc42f00558c295
title: Old electric guitar
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bass(props) {
  const { nodes, materials } = useGLTF("/models/old_electric_guitar.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.58, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[132.43, 962.95, 52.21]}
            rotation={[0.05, 0, 0]}
            scale={8.54}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Belaya002_Gitar_0.geometry}
              material={materials.Gitar}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Belaya002_Gitar_0_1.geometry}
              material={materials.Gitar}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Belaya002_Gitar_0_2.geometry}
              material={materials.Gitar}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Belaya002_Gitar_0_3.geometry}
              material={materials.Gitar}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Belaya002_Gitar_0_4.geometry}
              material={materials.Gitar}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/old_electric_guitar.glb");
