/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function BirthdayPhone(props) {
  const { nodes, materials } = useGLTF("/models/BirthdayPhone.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.003"]}
        scale={[0.92, 1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0, 0, -0.12]}
        scale={[0.92, 1, 0.2]}
      />
    </group>
  );
}

useGLTF.preload("/models/BirthdayPhone.glb");
