/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Calendar.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={[0.77, 0.77, -0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Days}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.White}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Calendar}
        scale={[0.77, 0.77, -0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.Material}
        position={[-0.44, 0.46, 0.2]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.15}
      />
    </group>
  );
}

useGLTF.preload("/Calendar.glb");
