/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Chibi(props) {
  const { nodes, materials } = useGLTF("/Chibi.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={49.36}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Add_low_Add_Mat_0.geometry}
              material={materials.Add_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ArmsBottom_low_ArmsBottom_Mat_0.geometry}
              material={materials.ArmsBottom_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ArmsTop_low_ArmsTop_Mat_0.geometry}
              material={materials.ArmsTop_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Blindfold_low_Blindfold_Mat_0.geometry}
              material={materials.Blindfold_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Bottom_low_Bottom_Mat_0.geometry}
              material={materials.Bottom_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cloth_low_Cloth_Mat_0.geometry}
              material={materials.Cloth_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ears_low_Ears_Mat_0.geometry}
              material={materials.Ears_Mat}
            >
              <group position={[0, -2.56, 0]} scale={1.11}>
                <group position={[0, 1.01, -0.06]} rotation={[0.07, 0, 0]}>
                  <group position={[0, 0.65, 0]} rotation={[0.04, 0, 0]}>
                    <group position={[0, 0.13, 0.02]} rotation={[-0.11, 0, 0]}>
                      <group
                        position={[0.02, 0.19, 0.11]}
                        rotation={[-2.26, 1.49, -1.26]}
                      >
                        <group
                          position={[-0.01, -0.01, 0.03]}
                          rotation={[0.09, -0.26, -0.09]}
                        >
                          <group
                            position={[-0.02, 0, 0.03]}
                            rotation={[-0.01, -0.57, 0]}
                          />
                        </group>
                      </group>
                      <group
                        position={[-0.02, 0.19, 0.11]}
                        rotation={[-2.26, -1.49, 1.26]}
                      >
                        <group
                          position={[0.01, -0.01, 0.03]}
                          rotation={[0.09, 0.26, 0.09]}
                        >
                          <group
                            position={[0.02, 0, 0.03]}
                            rotation={[-0.01, 0.57, 0]}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    position={[0.02, 0.6, 0.08]}
                    rotation={[-1.64, 0, -1.04]}
                  >
                    <group
                      position={[0.01, 0.2, -0.02]}
                      rotation={[2.07, 0.88, 2.93]}
                    >
                      <group
                        position={[-0.01, 0.69, 0]}
                        rotation={[3.11, 1.49, -2.56]}
                      />
                      <group
                        position={[-0.01, 0.7, -0.01]}
                        rotation={[1.72, 1.52, -1.27]}
                      />
                      <group
                        position={[-0.01, 0.7, -0.02]}
                        rotation={[0.59, 1.41, -0.27]}
                      />
                      <group
                        position={[0, 0.7, -0.04]}
                        rotation={[0.61, 1.32, -0.42]}
                      />
                    </group>
                  </group>
                  <group
                    position={[-0.02, 0.6, 0.08]}
                    rotation={[-1.64, 0, 1.04]}
                  >
                    <group
                      position={[-0.01, 0.2, -0.02]}
                      rotation={[1.17, -0.85, 2.57]}
                    >
                      <group
                        position={[0.01, 0.72, 0.03]}
                        rotation={[2.28, -1.38, 2.3]}
                      />
                      <group
                        position={[0.01, 0.72, 0.01]}
                        rotation={[1.8, -1.43, 1.91]}
                      />
                      <group
                        position={[0.01, 0.71, 0]}
                        rotation={[0.7, -1.42, 0.95]}
                      />
                      <group
                        position={[0.01, 0.7, -0.02]}
                        rotation={[0.48, -1.35, 0.86]}
                      />
                    </group>
                  </group>
                  <group
                    position={[0.1, 0.06, 0.04]}
                    rotation={[3, 0, -0.12]}
                  />
                  <group position={[-0.1, 0.06, 0.04]} rotation={[3, 0, 0]} />
                </group>
              </group>
            </mesh>
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HairBack_low_HairBack_Mat_0.geometry}
              material={materials.HairBack_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HairFront_low_HairFront_Mat_0.geometry}
              material={materials.HairFront_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head_low_Head_Mat_0.geometry}
              material={materials.Head_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Legs_low_Legs_Mat_0.geometry}
              material={materials.Legs_Mat}
            />
          </group>
          <group
            position={[-0.15, 0.9, -0.51]}
            rotation={[0.15, -0.12, -0.74]}
            scale={0.49}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Part1_low_Part1_Mat_0.geometry}
              material={materials.Part1_Mat}
            />
          </group>
          <group
            position={[-0.15, 0.9, -0.51]}
            rotation={[0.15, -0.12, -0.74]}
            scale={0.49}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Part2_low_Part2_Mat_0.geometry}
              material={materials.Part2_Mat}
            />
          </group>
          <group
            position={[-0.15, 0.9, -0.51]}
            rotation={[0.15, -0.12, -0.74]}
            scale={0.49}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Part3_low_Part3_Mat_0.geometry}
              material={materials.Part3_Mat}
            />
          </group>
          <group
            position={[-0.15, 0.9, -0.51]}
            rotation={[0.15, -0.12, -0.74]}
            scale={0.49}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Part4_low_Part4_Mat_0.geometry}
              material={materials.Part4_Mat}
            />
          </group>
          <group position={[0, 2.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Tail_low_Tail_Mat_0.geometry}
              material={materials.Tail_Mat}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Chibi.glb");
