/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Serg.Morgun (https://sketchfab.com/Serg.Morgun)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/drum-kit-99218427e7a2424ea8afc9b8c668a5c7
title: Drum Kit
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Drumps(props) {
  const { nodes, materials } = useGLTF("/models/Drums.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={100}>
            <group position={[1.19, 2.35, -0.02]} rotation={[0, 0, 0.1]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.polySurface1365_phong4_0.geometry}
                material={materials.phong4}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1378_phong4_0.geometry}
              material={materials.phong4}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.drums_lowpolySurface1269_phong5_0.geometry}
            material={materials.phong5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1386_phongE1_0.geometry}
            material={materials.phongE1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1055_blinn2_0.geometry}
            material={materials.blinn2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.polySurface1323_group20_group19_group20_lambert1_0.geometry
            }
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1387_lambert2_0.geometry}
            material={materials.lambert2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Drums.glb");
