/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function House(props) {
  const { nodes, materials } = useGLTF("/lil_house.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_1.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_2.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[0, 0.62, 0.03]}
        scale={[0.46, 0.37, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.003"]}
        position={[-0.01, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.002"]}
        position={[0, 0.2, -0.4]}
        scale={[0.66, 0.66, 0.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Material}
        position={[0, 0.21, -0.4]}
        scale={[0.6, 0.51, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.002"]}
        position={[-0.74, 1.07, 0.08]}
        scale={[0.19, 0.19, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Material.002"]}
        position={[0, 0.62, 0.03]}
        scale={[0.46, 0.37, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Material}
        position={[0, 0.62, 0.03]}
        scale={[0.46, 0.37, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Material.002"]}
        position={[0, 0.62, 0.11]}
        scale={[0.46, 0.37, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Material.004"]}
        position={[0, 0.21, -0.4]}
        scale={[0.6, 0.51, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.002"]}
        position={[-0.89, 1.2, 0.53]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.28, -0.05, 0.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Material}
        position={[-0.88, 1.2, 0.52]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.28, -0.05, 0.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.planks}
        position={[0.08, 0.07, 0.82]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.17, 0.2, -0.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.007"]}
        position={[0.78, 0.59, -1.09]}
        rotation={[Math.PI / 2, 0, -3.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Material.007"]}
        position={[-1.1, 0.53, -0.73]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/lil_house.glb");
