/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/hydrant.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["fire-hydrant.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003_1.geometry}
        material={materials["bolt.002"]}
      />
    </group>
  );
}

useGLTF.preload("/hydrant.glb");
