/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function LesPaul(props) {
  const { nodes, materials } = useGLTF("/models/LesPaul.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.13, 0.35]} rotation={[0, 1.56, 1.37]}>
        <group position={[2.05, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane.geometry}
            material={materials["Preto Braco"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_1.geometry}
            material={materials["Plastico Branco"]}
          />
        </group>
        <group
          position={[0.52, 0, 0.42]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials["Preto Base"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012_1.geometry}
            material={materials["Metal Dorado"]}
          />
        </group>
        <group position={[0.96, 0.2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={materials["Metal Dorado"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={materials["Metal Preto"]}
          />
        </group>
        <group position={[1.4, 0.2, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={materials["Metal Dorado"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={materials["Metal Preto"]}
          />
        </group>
        <group position={[1.59, 0.2, -0.33]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003.geometry}
            material={materials["Metal Cromo"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003_1.geometry}
            material={materials["Plastico Branco"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003_2.geometry}
            material={materials.Chave}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Corda1.geometry}
          material={materials["Metal Cromo"]}
          position={[0.55, 0.22, -0.1]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Corda2.geometry}
          material={materials["Metal Cromo"]}
          position={[0.55, 0.22, -0.06]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Corda3.geometry}
          material={materials["Metal Cromo"]}
          position={[0.55, 0.22, -0.02]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Corda4.geometry}
          material={materials["Metal Cromo"]}
          position={[0.55, 0.22, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Corda5.geometry}
          material={materials["Metal Cromo"]}
          position={[0.55, 0.22, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Corda6.geometry}
          material={materials["Metal Cromo"]}
          position={[0.55, 0.22, 0.1]}
        />
        <group position={[2.05, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert.geometry}
            material={materials["Preto Base"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert_1.geometry}
            material={materials["Plastico Branco"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DetalhesEscala.geometry}
          material={materials["Metal Fosco"]}
          position={[1.61, 0.21, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Escala.geometry}
          material={materials.Escala}
          position={[2.05, 0, 0]}
        />
        <group position={[1.18, 0.2, 0.31]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert007.geometry}
            material={materials["Plastico Branco"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert007_1.geometry}
            material={materials["Metal Dorado"]}
          />
        </group>
        <group position={[2.05, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert003.geometry}
            material={materials["Metal Dorado"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert003_1.geometry}
            material={materials["Metal Preto"]}
          />
        </group>
        <group position={[0.59, 0.2, 0.33]} rotation={[0, 1.52, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle004.geometry}
            material={materials["Knob Base"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle004_1.geometry}
            material={materials["Knob Prata Volume"]}
          />
        </group>
        <group
          position={[0.44, 0.2, 0.51]}
          rotation={[-Math.PI, 1.2, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002.geometry}
            material={materials["Knob Base"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_1.geometry}
            material={materials["Knob Prata Tone"]}
          />
        </group>
        <group position={[0.7, 0.2, 0.51]} rotation={[0, 0.67, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle006.geometry}
            material={materials["Knob Base"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle006_1.geometry}
            material={materials["Knob Prata Volume"]}
          />
        </group>
        <group position={[0.33, 0.2, 0.33]} rotation={[0, 0.79, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle007.geometry}
            material={materials["Knob Base"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle007_1.geometry}
            material={materials["Knob Prata Tone"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pestana.geometry}
          material={materials["Plastico Branco"]}
          position={[3.47, 0.13, 0]}
          rotation={[0, 0, -0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ponte.geometry}
          material={materials["Metal Dorado"]}
          position={[0.73, 0.23, 0]}
        />
        <group position={[0, 0.1, -0.01]} scale={0.03}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001.geometry}
            material={materials["Metal Dorado"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_1.geometry}
            material={materials["Plastico Preto"]}
          />
        </group>
        <group
          position={[1.83, 0.1, -0.25]}
          rotation={[Math.PI, -0.26, Math.PI]}
          scale={0.03}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001.geometry}
            material={materials["Metal Dorado"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_1.geometry}
            material={materials["Plastico Preto"]}
          />
        </group>
        <group position={[3.49, 0.12, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008.geometry}
            material={materials["Preto Base"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_1.geometry}
            material={materials["Metal Dorado"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_2.geometry}
            material={materials["Plastico Branco"]}
          />
        </group>
        <group
          position={[-0.01, -0.37, 0]}
          rotation={[-Math.PI / 2, -0.2, -Math.PI / 2]}
          scale={0.3}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials["Metal Preto"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials["Plastico Preto"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["Metal Cromo"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tarraxa.geometry}
          material={materials["Metal Dorado"]}
          position={[3.88, -0.06, 0]}
          rotation={[Math.PI / 2, 1.31, -Math.PI / 2]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Traste.geometry}
          material={materials["Metal Cromo"]}
          position={[2.25, 0.19, 0]}
          rotation={[0, 0, -0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TravaCordas.geometry}
          material={materials["Metal Fosco"]}
          position={[0.54, 0.22, 0]}
          rotation={[2.27, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/LesPaul.glb");
