/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Okayest (https://sketchfab.com/okayest)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-school-microphone-451aa63c7cea47c998a8058e0940349d
title: Old School Microphone
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Mic(props) {
  const { nodes, materials } = useGLTF("/models/microphone.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 5.92, -0.13]} scale={[0.08, 0.1, 0.08]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.metal1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.metal1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.metal1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.metal1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.metal1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.metal1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.metal2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.metal2}
            />
          </group>
          <group position={[0, 4.46, -0.08]} scale={[0.03, 0.39, 0.03]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials.metal1}
            />
          </group>
          <group position={[0, 4.9, -0.09]} scale={0.07}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.cable}
            />
          </group>
          <group position={[0, 5.21, -0.12]} scale={[0.08, 0.16, 0.07]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.cable}
            />
          </group>
          <group position={[0, 5.21, -0.15]} scale={[0.05, 0.09, 0.05]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.metal1}
            />
          </group>
          <group position={[0, 5.21, -0.18]} scale={[0.03, 0.07, 0.04]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.swirch}
            />
          </group>
          <group position={[0, 5.51, -0.09]} scale={[0.04, 0.06, 0.06]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials.metal1}
            />
          </group>
          <group position={[0, 5.51, -0.09]} scale={[0.1, 0.04, 0.04]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.metal1}
            />
          </group>
          <group
            position={[0, 5.61, 0.02]}
            rotation={[-Math.PI / 3, 0, 0]}
            scale={0.04}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials.metal1}
            />
          </group>
          <group position={[0, 5.51, -0.09]} scale={[0.12, 0.05, 0.05]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_29.geometry}
              material={materials.metal1}
            />
          </group>
          <group
            position={[0, 5.37, 0.07]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.67, 0.67, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials.cable}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/microphone.glb");
