/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Office(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Office.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Trash_Can"
          castShadow
          receiveShadow
          geometry={nodes.Trash_Can.geometry}
          material={materials["Material.003"]}
          position={[-3.16, 0.22, -4.15]}
          scale={0.54}
        />
        <mesh
          name="Trash_Can001"
          castShadow
          receiveShadow
          geometry={nodes.Trash_Can001.geometry}
          material={materials["Table Legs"]}
          position={[-3.17, 1.02, -4.1]}
          scale={[0.69, 0.54, 0.69]}
        />
        <mesh
          name="Trash_Can002"
          castShadow
          receiveShadow
          geometry={nodes.Trash_Can002.geometry}
          material={materials["Table Legs"]}
          position={[-3.13, 0.03, -3.75]}
          scale={[0.33, 0.26, 0.33]}
        />
        <group
          name="Legs"
          position={[-1.77, -0.18, -4.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[-1.32, 0.04, -0.16]}
        >
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["Table Legs"]}
          />
          <mesh
            name="Cube001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["Table Top"]}
          />
        </group>
        <mesh
          name="Table_Top001"
          castShadow
          receiveShadow
          geometry={nodes.Table_Top001.geometry}
          material={materials.Metal}
          position={[-0.65, 1.68, -3.94]}
          scale={[2.71, 0.17, 1.32]}
        />
        <group
          name="Table_Top002"
          position={[1.53, 0.74, -4.34]}
          scale={[0.8, 0.91, 0.91]}
        >
          <mesh
            name="Cube008_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube008_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Cube008_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube008_2.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Cube008_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube008_3.geometry}
            material={materials["Table Legs"]}
          />
        </group>
        <mesh
          name="Table_Top003"
          castShadow
          receiveShadow
          geometry={nodes.Table_Top003.geometry}
          material={materials["Table Top"]}
          position={[-0.65, 1.68, -3.94]}
          scale={[2.71, 0.17, 1.32]}
        />
        <group
          name="Mini_Table"
          position={[0.42, 2.71, -4.92]}
          scale={[1.97, 0.1, 0.39]}
        >
          <mesh
            name="Cube011_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1.geometry}
            material={materials["Table Top"]}
          />
          <mesh
            name="Cube011_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_2.geometry}
            material={materials["Table Legs"]}
          />
        </group>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Floor}
          position={[0.56, 5.24, -0.05]}
          scale={5.53}
        />
        <mesh
          name="Circle002"
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials.Leaf}
          position={[2.75, 2.86, -4.75]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name="PC"
          castShadow
          receiveShadow
          geometry={nodes.PC.geometry}
          material={materials["Material.004"]}
          position={[0.42, -0.19, -4.25]}
          scale={1.32}
        />
        <mesh
          name="Table_Top006"
          castShadow
          receiveShadow
          geometry={nodes.Table_Top006.geometry}
          material={materials.Keyboard}
          position={[0.42, 2.29, -3.79]}
          scale={[0.86, 0.05, 0.38]}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube003"
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube006"
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube007"
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube008"
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={nodes.Cube009.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube010"
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube011"
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={nodes.Cube012.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube013"
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={nodes.Cube013.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube014"
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={nodes.Cube014.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube015"
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={nodes.Cube015.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube016"
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={nodes.Cube016.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube017"
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={nodes.Cube017.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube018"
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={nodes.Cube018.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube019"
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={nodes.Cube019.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube020"
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={nodes.Cube020.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube021"
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={nodes.Cube021.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube022"
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={nodes.Cube022.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube023"
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={nodes.Cube023.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube024"
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={nodes.Cube024.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube025"
          castShadow
          receiveShadow
          geometry={nodes.Cube025.geometry}
          material={nodes.Cube025.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube026"
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={nodes.Cube026.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube027"
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={nodes.Cube027.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube028"
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={nodes.Cube028.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube029"
          castShadow
          receiveShadow
          geometry={nodes.Cube029.geometry}
          material={nodes.Cube029.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube030"
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={nodes.Cube030.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube031"
          castShadow
          receiveShadow
          geometry={nodes.Cube031.geometry}
          material={nodes.Cube031.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube032"
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={nodes.Cube032.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube033"
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={nodes.Cube033.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube034"
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={nodes.Cube034.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube035"
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={nodes.Cube035.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube036"
          castShadow
          receiveShadow
          geometry={nodes.Cube036.geometry}
          material={nodes.Cube036.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube037"
          castShadow
          receiveShadow
          geometry={nodes.Cube037.geometry}
          material={nodes.Cube037.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube038"
          castShadow
          receiveShadow
          geometry={nodes.Cube038.geometry}
          material={nodes.Cube038.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube039"
          castShadow
          receiveShadow
          geometry={nodes.Cube039.geometry}
          material={nodes.Cube039.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube040"
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={nodes.Cube040.material}
          position={[-0.21, 2.34, -4]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube045"
          castShadow
          receiveShadow
          geometry={nodes.Cube045.geometry}
          material={nodes.Cube045.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube046"
          castShadow
          receiveShadow
          geometry={nodes.Cube046.geometry}
          material={nodes.Cube046.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube047"
          castShadow
          receiveShadow
          geometry={nodes.Cube047.geometry}
          material={nodes.Cube047.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube048"
          castShadow
          receiveShadow
          geometry={nodes.Cube048.geometry}
          material={nodes.Cube048.material}
          position={[-0.27, 2.34, -4.01]}
          rotation={[-3.03, 0, 0]}
          scale={-0.02}
        />
        <mesh
          name="Cube041"
          castShadow
          receiveShadow
          geometry={nodes.Cube041.geometry}
          material={materials["White Plastic"]}
          position={[-1.87, 2.32, -4.95]}
          rotation={[0, -0.02, 0]}
          scale={0.14}
        />
        <mesh
          name="Cube042"
          castShadow
          receiveShadow
          geometry={nodes.Cube042.geometry}
          material={materials["Table Legs"]}
          position={[-1.72, 1.89, -5.01]}
          rotation={[-0.03, 0.07, 0.13]}
          scale={0.16}
        />
        <mesh
          name="Cube043"
          castShadow
          receiveShadow
          geometry={nodes.Cube043.geometry}
          material={materials["Table Legs"]}
          position={[-2.13, 1.97, -4.78]}
          rotation={[-1.26, -1, -1.1]}
          scale={0.16}
        />
        <mesh
          name="Cube044"
          castShadow
          receiveShadow
          geometry={nodes.Cube044.geometry}
          material={materials["Table Legs"]}
          position={[-1.52, 1.99, -4.71]}
          rotation={[-0.64, 0.14, 0.69]}
          scale={0.16}
        />
        <group
          name="Top_Shelf"
          position={[0.42, 6.39, -5.14]}
          scale={[3.77, 0.1, 0.39]}
        >
          <mesh
            name="Cube068_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube068_1.geometry}
            material={materials["Table Top"]}
          />
          <mesh
            name="Cube068_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube068_2.geometry}
            material={materials["Table Legs"]}
          />
        </group>
        <group
          name="Cylinder001"
          position={[-1.77, 6.49, -5.2]}
          scale={[0.28, 0.01, 0.28]}
        >
          <mesh
            name="Cylinder001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Cylinder001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group
          name="Cube050"
          position={[1.04, 6.89, -5.13]}
          scale={[0.26, 0.04, 0.26]}
        >
          <mesh
            name="Cube070_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube070_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Cube070_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube070_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Cube049"
          position={[1.81, 7.18, -5.12]}
          scale={[0.46, 0.07, 0.46]}
        >
          <mesh
            name="Cube071_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube071_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Cube071_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube071_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          name="Cube051"
          castShadow
          receiveShadow
          geometry={nodes.Cube051.geometry}
          material={materials.Book}
          position={[-0.1, 6.83, -5.17]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.33, -0.04, 0.21]}
        />
        <mesh
          name="Cube052"
          castShadow
          receiveShadow
          geometry={nodes.Cube052.geometry}
          material={materials.Metal}
          position={[0, 6.83, -5.17]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.33, -0.04, 0.21]}
        />
        <mesh
          name="Cube053"
          castShadow
          receiveShadow
          geometry={nodes.Cube053.geometry}
          material={materials["Material.005"]}
          position={[0.2, 6.83, -5.17]}
          rotation={[0, 0, -1.26]}
          scale={[0.33, -0.04, 0.21]}
        />
        <mesh
          name="Cube054"
          castShadow
          receiveShadow
          geometry={nodes.Cube054.geometry}
          material={materials.Metal}
          position={[-0.56, 6.54, -5.06]}
          rotation={[0, -0.6, -Math.PI]}
          scale={[0.33, -0.04, 0.21]}
        />
        <mesh
          name="Cube055"
          castShadow
          receiveShadow
          geometry={nodes.Cube055.geometry}
          material={materials["Material.004"]}
          position={[0.56, 5.28, -0.05]}
          scale={5.53}
        />
        <mesh
          name="Cube057"
          castShadow
          receiveShadow
          geometry={nodes.Cube057.geometry}
          material={materials.Floor}
          position={[0.56, 5.24, -0.05]}
          scale={5.53}
        />
        <mesh
          name="Cube056"
          castShadow
          receiveShadow
          geometry={nodes.Cube056.geometry}
          material={materials["Material.004"]}
          position={[0.46, 0.86, -1.26]}
          rotation={[0, -1.33, 0]}
          scale={[0.81, 0.17, 0.81]}
        />
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Table Legs"]}
          position={[0.5, 0.32, -1.02]}
          scale={0.18}
        />
        <mesh
          name="Cube058"
          castShadow
          receiveShadow
          geometry={nodes.Cube058.geometry}
          material={materials["Table Top"]}
          position={[5.01, 0.75, 2.49]}
          scale={[1, 1, -2.06]}
        />
        <mesh
          name="Cube059"
          castShadow
          receiveShadow
          geometry={nodes.Cube059.geometry}
          material={materials["Material.006"]}
          position={[5.01, 0.75, 2.49]}
          scale={[1, 1, -2.06]}
        />
        <mesh
          name="Cube060"
          castShadow
          receiveShadow
          geometry={nodes.Cube060.geometry}
          material={nodes.Cube060.material}
          position={[5.53, 1.02, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube061"
          castShadow
          receiveShadow
          geometry={nodes.Cube061.geometry}
          material={nodes.Cube061.material}
          position={[5.53, 1.02, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube062"
          castShadow
          receiveShadow
          geometry={nodes.Cube062.geometry}
          material={nodes.Cube062.material}
          position={[5.53, 1.02, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube063"
          castShadow
          receiveShadow
          geometry={nodes.Cube063.geometry}
          material={nodes.Cube063.material}
          position={[5.53, 1.02, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube064"
          castShadow
          receiveShadow
          geometry={nodes.Cube064.geometry}
          material={nodes.Cube064.material}
          position={[5.53, 1.02, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube065"
          castShadow
          receiveShadow
          geometry={nodes.Cube065.geometry}
          material={nodes.Cube065.material}
          position={[5.53, 1.02, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube066"
          castShadow
          receiveShadow
          geometry={nodes.Cube066.geometry}
          material={nodes.Cube066.material}
          position={[5.53, 0.96, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube067"
          castShadow
          receiveShadow
          geometry={nodes.Cube067.geometry}
          material={nodes.Cube067.material}
          position={[5.53, 1.02, 1.32]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube068"
          castShadow
          receiveShadow
          geometry={nodes.Cube068.geometry}
          material={nodes.Cube068.material}
          position={[5.75, 1.15, 4.3]}
          scale={[-0.48, -0.48, 0.98]}
        />
        <mesh
          name="Cube069"
          castShadow
          receiveShadow
          geometry={nodes.Cube069.geometry}
          material={materials.Leaf}
          position={[4.65, 1.12, 0.93]}
          scale={[0.07, 0.24, 0.07]}
        />
        <mesh
          name="Cube070"
          castShadow
          receiveShadow
          geometry={nodes.Cube070.geometry}
          material={materials.Leaf}
          position={[5.46, 1.12, 1.68]}
          rotation={[-Math.PI, 0.56, -Math.PI]}
          scale={[0.07, 0.24, 0.07]}
        />
        <mesh
          name="Cube071"
          castShadow
          receiveShadow
          geometry={nodes.Cube071.geometry}
          material={materials.Leaf}
          position={[5.68, 1.12, 0.58]}
          rotation={[0, 0.58, 0]}
          scale={[0.07, 0.24, 0.07]}
        />
        <mesh
          name="Cube072"
          castShadow
          receiveShadow
          geometry={nodes.Cube072.geometry}
          material={materials.Leaf}
          position={[4.66, 1.12, 3.03]}
          rotation={[0, 0.58, 0]}
          scale={[0.07, 0.24, 0.07]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[5.1, 1.78, 2.62]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.11}
        />
        <mesh
          name="Cylinder002"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials["Table Top"]}
          position={[4.8, 1.75, -4.35]}
          scale={[1, 0.05, 1]}
        />
        <mesh
          name="Cylinder003"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials["Table Top"]}
          position={[4.8, 0.33, -4.35]}
          rotation={[-0.01, 0, 0.01]}
          scale={[1, 0.05, 1]}
        />
        <mesh
          name="Cylinder004"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials.Metal}
          position={[3.99, -0.25, -4.35]}
          rotation={[0, 0, -0.08]}
          scale={[0.08, 0.01, 0.08]}
        />
        <mesh
          name="Cylinder005"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials.Metal}
          position={[4.8, -0.25, -3.54]}
          rotation={[-0.08, Math.PI / 2, 0]}
          scale={[0.08, 0.01, 0.08]}
        />
        <mesh
          name="Cylinder006"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.Metal}
          position={[5.62, -0.25, -4.35]}
          rotation={[Math.PI, 0, 3.06]}
          scale={[0.08, 0.01, 0.08]}
        />
        <mesh
          name="Cylinder007"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials.Metal}
          position={[4.8, -0.25, -5.16]}
          rotation={[0.08, -Math.PI / 2, 0]}
          scale={[0.08, 0.01, 0.08]}
        />
        <mesh
          name="Cube073"
          castShadow
          receiveShadow
          geometry={nodes.Cube073.geometry}
          material={materials.Metal}
          position={[4.91, 1.89, -3.9]}
          rotation={[0, -0.6, -Math.PI]}
          scale={[0.33, -0.04, 0.21]}
        />
        <mesh
          name="Cube074"
          castShadow
          receiveShadow
          geometry={nodes.Cube074.geometry}
          material={materials["Table Legs"]}
          position={[5.14, 1.93, -4.04]}
          rotation={[1.04, -0.05, 1.23]}
          scale={0.16}
        />
        <mesh
          name="Cylinder008"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={nodes.Cylinder008.material}
          position={[4.2, 1.91, -4.24]}
          rotation={[0, 0.65, 0]}
          scale={0.11}
        />
        <mesh
          name="Cube077"
          castShadow
          receiveShadow
          geometry={nodes.Cube077.geometry}
          material={materials.Metal}
          position={[4.88, 1.97, -3.98]}
          rotation={[0, -0.55, -Math.PI]}
          scale={[0.33, -0.04, 0.21]}
        />
        <mesh
          name="Circle001"
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["Material.003"]}
          position={[2.75, 2.86, -4.75]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name="Circle003"
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials.Leaf}
          position={[2.75, 2.86, -4.75]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name="Circle004"
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials.Leaf}
          position={[2.75, 2.86, -4.75]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name="Circle005"
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials.Leaf}
          position={[2.75, 2.86, -4.75]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name="Circle006"
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={materials.Leaf}
          position={[2.75, 2.86, -4.75]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name="Text"
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={nodes.Text.material}
          position={[1.45, 2.22, -3.52]}
        />
        <mesh
          name="Text001"
          castShadow
          receiveShadow
          geometry={nodes.Text001.geometry}
          material={nodes.Text001.material}
          position={[-2.29, 2.19, -3.55]}
        />
        <mesh
          name="Screen"
          castShadow
          receiveShadow
          geometry={nodes.Screen.geometry}
          material={materials.PC}
          position={[0.42, -0.19, -4.25]}
          scale={1.32}
        />
        <mesh
          name="Plane001"
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.PC}
          position={[6.09, 6.15, -0.2]}
          rotation={[Math.PI / 2, 0, -1.57]}
          scale={[1.42, 1.42, 2.56]}
        />
        <group
          name="Picture_Frame_2"
          position={[5.42, 3.25, 2.31]}
          rotation={[-0.01, -0.01, -0.54]}
          scale={[-0.04, 0.48, 0.42]}
        >
          <mesh
            name="Cube107"
            castShadow
            receiveShadow
            geometry={nodes.Cube107.geometry}
            material={materials.Picture}
          />
          <mesh
            name="Cube107_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube107_1.geometry}
            material={materials["Table Top"]}
          />
        </group>
        <group
          name="Picture__2"
          position={[5.27, 3.25, 1.14]}
          rotation={[-0.01, 0.45, -0.53]}
          scale={[-0.04, 0.48, 0.42]}
        >
          <mesh
            name="Cube103"
            castShadow
            receiveShadow
            geometry={nodes.Cube103.geometry}
            material={materials["Table Top"]}
          />
          <mesh
            name="Cube103_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube103_1.geometry}
            material={materials["Material.007"]}
          />
        </group>
        <mesh
          name="Plane002"
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials["White Board"]}
          position={[6.09, 6.15, -0.2]}
          rotation={[Math.PI / 2, 0, -1.57]}
          scale={[1.42, 1.42, 2.56]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Office.glb");
