/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: TheGiwi (https://sketchfab.com/TheGiwi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pa-speakers-low-poly-071eb97ed2bf429c821a8ebfcf3554d4
title: PA Speakers Low-Poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Speakers(props) {
  const { nodes, materials } = useGLTF("/Speakers.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.08, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.PA_speakers}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Speakers.glb");
