/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Vibes(props) {
  const { nodes, materials } = useGLTF("/models/Vibes.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_1.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_2.geometry}
        material={materials.Gold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Gold}
        position={[-2.9, 5.79, 0]}
        rotation={[0, 0, 0.81]}
        scale={[0.12, 2.49, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Gold}
        position={[2.35, 0.76, 0]}
        scale={[0.41, 0.41, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Gold}
        position={[-4.53, 7.43, 0]}
        rotation={[-0.01, 0, -0.05]}
        scale={[0.58, 0.58, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Gold}
        position={[-4.91, 7.76, 0]}
        scale={[0.41, 0.41, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.Gold}
        position={[-3.34, 5.47, 1.12]}
        rotation={[1.66, -0.38, 0.07]}
        scale={1.49}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials.Gold}
        position={[-2.1, 2.9, 1.12]}
        rotation={[1.66, -0.38, 0.07]}
        scale={1.49}
      />
    </group>
  );
}

useGLTF.preload("/models/Vibes.glb");
